options:
  download-url:
    type: string
    default: "https://downloads.plex.tv/plex-media-server/1.4.3.3433-03e4cfa35/plexmediaserver_1.4.3.3433-03e4cfa35_amd64.deb"
    description: "The URL to download plex from"
#  boolean-option:
#    type: boolean
#    default: False
#    description: "A short description of the configuration option"
#  int-option:
#    type: int
#    default: 9001
#    description: "A short description of the configuration option"

