options:
  download-url:
    type: string
    default: ""
    #default: "https://downloads.plex.tv/plex-media-server/1.4.3.3433-03e4cfa35/plexmediaserver_1.4.3.3433-03e4cfa35_amd64.deb"
    description: "The URL to download plex from"
  keep-debs:
    type: int
    default: 1
    description: "Number of .deb packages to keep locally, set to 0 for none"
  user-name:
    type: string
    default: ""
    description: "Username for plex log-in, provided via relation to other services if set"
  passwd:
    type: string
    default: ""
    description: "Password for plex log-in, provided via relation to other services if set"
