options:
  download-url:
    type: string
    default: "https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu"
    description: "The URL to download plex from, this likely should not change."
  keep-debs:
    type: int
    default: 1
    description: "Number of .deb packages to keep locally, Note have at least 1 deb is recommended for updates."
  user-name:
    type: string
    default: ""
    description: "Username for plex log-in, provided via relation to other services if set"
  passwd:
    type: string
    default: ""
    description: "Password for plex log-in, provided via relation to other services if set"
  plex-pass-token:
    type: string
    default: ""
    description: "A token to download plex-pass releases"
  update-cron:
    type: string
    default: "@daily"
    description: "Interval to check for plex updates, takes a cron compatible string"
  restore-db:
    type: boolean
    default: False
    description: "Restore a databse from previous install"
  restore-config:
    type: boolean
    default: False
    description: "Restore a configureation from previous install"
